//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudeWithAngular.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestingDBEntities : DbContext
    {
        public TestingDBEntities()
            : base("name=TestingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeAudit> EmployeeAudits { get; set; }
        public virtual DbSet<EmployeeRecord> EmployeeRecords { get; set; }
        public virtual DbSet<salarytest> salarytests { get; set; }
        public virtual DbSet<tblFileDetail> tblFileDetails { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
